const voices = {
    "Aria": "9BWtsMINqrJLrRacOk9x",
    "Sarah": "EXAVITQu4vr4xnSDxMaL",
    "Laura": "FGY2WhTYpPnrIDTdsKH5",
    "Charlie": "IKne3meq5aSn9XLyUdCD",
    "George": "JBFqnCBsd6RMkjVDRZzb",
    "Callum": "N2lVS1w4EtoT3dr4eOWO",
    "River": "SAz9Hcvj6GT2YYXdXww",
    "Liam": "TX3LPaxmHKxFdv7VOQHJ",
    "Charlotte": "XB0fDUnXU5powFXDhCwa",
    "Alice": "Xb7hH8MSUJpSbSDYk0k2",
    "Matilda": "XrExE9yKIg1WjnnlVkGX",
    "Will": "bIHbv24MWmeRgasZH58o",
    "Jessica": "cgSgspJ2msm6clMCkdW9",
    "Eric": "cjVigY5qzO86Huf0OWal",
    "Chris": "iP95p4xoKVk53GoZ742B",
    "Brian": "nPczCjzI2devNBz1zQrb",
    "Daniel": "onwK4e9ZLuTAKqWW03F9",
    "Lily": "pFZP5JQG7iQjIQuC4Bku",
    "Bill": "pqHfZKP75CvOlQylNhV4",
    "ANT Female 1.9.25": "TgFX4XZf9Igy6UFbbcMK",
    "Anthony Debt Clone": "O6WbAkKMlNRjCFJCkSP9",
    "Ant Mail Girl": "IAfoAZAXEjSH5d5RZIGK",
    "AWFEMALE": "vBne7F8T4WH6mGX1Mxhr",
    "Aaden - Tutorials & Chatbots": "LB3SchLS4lHotJg4GcZW",
    "Adam Stone - late night radio": "NFG5qt843uXKj4pFvR7C",
    "Aahmed ASMR": "68Z7Qr44IalOOUuVAR8R",
    "Andrea": "JpTREGmjdWHqVqT2XCOk",
    "Andrew - Smooth audio books": "gUABw7pXQjhjt0kNFBTF",
    "ATTANK": "Z7HhYXzYeRsQk3RnXqiG",
    "Alora": "4LSkjQYlOwjbFhuGrocm",
    "Adam - American Male": "ookcfIYgQDpBT5ueX6gr",
    "Barb AR": "HDG52NKJ1gUxmK5oadiL",
    "Aurelian Vox - Pro AI Technology Music ": "knOo4XX4oHnEyZZ5cjwk",
    "Arabella": "Z3R5wn05IrDiVCyEkUrK",
    "Arthur – American Male Narrator": "C1npRmjB19a6yNkEucvx",
    "Bristal": "eNINoK5Xd7oEA0MbRnuz",
    "Bill Audiobook Oxley": "KStQ5J0QpMyuoKkTnbDO",
    "Blaire": "RPdRfxxQOaNxn1LtRQqm",
    "Art Vandelay - fun and amusing": "97uzMxwDRAr8GfhZdNd7",
    "Brian: Very Realistic Reader": "UGTtbzgh3HObxRjWaSpr",
    "Bill Oxley - Mature American male": "T5cu6IU92Krx4mh43osx",
    "Austin - Dramatic Narration": "NMilCCbfoygNnI2VZ7ME",
    "Annie": "gfEDWsEwCATK3cT3E5Rn",
    "Chloe": "Ha9f2JUQ4LL1bw2ZcNjS",
    "Cal - Deep and Calming": "Fxt4GZnlXkUGMtWSYIcm",
    "Christian": "6xPz2opT0y5qtoRh1U1Y",
    "Deep Dave - Low & Confident": "Hbb2NXaf6CKJnlEHYM1D",
    "Constantino - Deep, Smooth, Conversational": "ApsbCjXt5HguctE80a0i",
    "Denzel - Deep, Masculine & Natural": "7sXif1ZLnLgbMgmFvs2G",
    "Cat - Droll and Dry": "54Cze5LrTSyLgbO6Fhlc",
    "Drew - Deep, Soothing, Guided Meditation": "wgHvco1wiREKN0BdyVx5",
    "David Castlemore - Newsreader and Educator": "XjLkpWUlnhS8i7gGz3lZ",
    "David - Mature, Engaging Male Voice (American accent)": "asDeXBMC8hUkhqqL7agO",
    "Educational Elias - Informative & Engaging": "bYS7cEY0uRew5lIOkGCu",
    "Edward": "2BJW5coyhAzSr8STdHbE",
    "Brandon - Professional American Male": "IMd3WihrJpmKaNSM1WHx",
    "Alex - Young American Male": "yl2ZDV1MzN4HbQJbMihG",
    "Frank Clone T": "s0VNLNCvBvERdwxQh1Bp",
    "Dyan - Calm and Soothing": "Gympn2UbmkJD4IHh5kzM",
    "Enrique": "Z7tQdvLS6QRQRjTLVY3x",
    "Denis - Authoritative and Deep Narrator": "NFZEBjyD4q0HVW4Atr6H",
    "Ethan Thomas Jung - American Male Teenager": "LhgPT1LS4EbAOTFHXOz1",
    "Giggles McGee - Wacky Cartoon Fun for Children's Content": "VE5rsMNTeE1frCCSXNIC",
    "Grandpa Spuds Oxley": "NOpBlnGInO9m6vDvFkFC",
    "HandrailSupport": "mrmh5i7zNpOwftrj8xdS",
    "James Clone": "je427wuabqlvQhyauHJ7",
    "Hope - upbeat and clear": "tnSpp4vdxKPjI9w0GnoV",
    "Bill Oxley - a powerful and confident voice that demands attention.": "6EW6z8IiJRtePnNUNPKW",
    "Hobbs - Casual Narration": "1YBpxMFAafA83t7u1xof",
    "JM - Husky & Engaging (2025-01-25_1100)": "EkK5I93UQWFDigLMpZcX",
    "Jack the Pirate": "tVkOo4DLgZb89qB0x4qP",
    "Illya - Soft and neutral": "CnV6BQOHeZCIv4McSXDH",
    "Jason - Calm and Informative": "PEj4Y2fjoqvsletcfytQ",
    "Jim": "ilvTFVoclEf6DFs61e1m",
    "Joe Podcast - Natural Conversation": "pujH7g2H19Q7U8Gevr98",
    "John Doe Deep": "EiNlNiXeDU1pqqOPrYMO",
    "Jordan (Popular) for Podcast, Ad, Video, Faceless Content": "ScZQf6C8aVzMf60NZQVk",
    "Joe": "UN88xMc1MbHmw9jNdYUX",
    "Harrison Gale – The Velvet Voice: deep, resonant, powerful, smooth, rich, storytelling, narrator": "fCxG8OHm4STbIsWe4aT9",
    "Jessica Anne Bogart - Narration. A VO Pro. Confident. Conversational. ": "lxYfHSkYm1EzQzGhdbfc",
    "Joseph - Smooth, calm, and perfect for storytelling.": "srqXQmVZdKporFRQUBMI",
    "John Mansfield": "jD9ZLAx3sVOQk9LCF0zD",
    "Jeff": "k9073AMdU5sAUtPMH1il",
    "Juniper": "aMSt68OGf4xUZAnLpTU8",
    "Karla - Breathy, Expressive American Young Woman": "0TfZ4rvne3QI7UjDxVkM",
    "Jay Johnson": "aeMZw5mFolEDifP9XfB4",
    "Kix On Air Voice": "0MmmY3MXTyPRLNhYh5Wb",
    "Kyana Cook": "3wZbmt7q1ZGa1v0w9nvu",
    "Ken Franson - Professional Narration": "kJKMPwrIKzwVkMKOfRtr",
    "Liberty - Expressive, Youthful, Dynamic": "6fNaivppJl6CJRec5L9j",
    "MaleAWVOICE ": "wmbYb4TsT0z8LLQkU6EV",
    "LiveChi Voiceover": "LHgFk7RaIiyNE5I3pC1d",
    "Haven Sands": "x8xv0H8Ako6Iw3cKXLoC",
    "Lowy - soothing, gentle, and warm": "24EI9FmmGvJruwUi7TJM",
    "Lucas - Expressive, Casual, and Neutral": "s0XGIcqmceN2l7kjsqoZ",
    "Luca - calm, soothing, steady": "4JVOFy4SLQs9my0OLhEw",
    "Laurent Eggers": "QPMFC9ichxmWL67JBKLq",
    "Marcus - Young American Male": "egdQA558M1sKeWXK6DIf",
    "Markmont.": "rTOopItG6FIkKMIVxsl5",
    "Matt - Strong Narration and Storytelling": "8iDUAV5slUpRv30f3cyz",
    "Melina_CTC": "jwjWpCFQUCpnHneBySsF",
    "Mark - Natural Conversations": "UgBBYS2sOqTuMpoF3BR0",
    "Mellow Matt": "IsEXLHzSvLH9UMB6SLHj",
    "Maya: Young, shy, introspective but a bit anxious, like your introvert girlfriend": "tJ2B69tloiOhZn8Gk9Lp",
    "Michele": "hQlCFoDMoIKoDA8Hxcnh",
    "Middle aged female aw old": "hiAYfvIeaYexyKILh7vQ",
    "New Female Clone 3.11": "SKxC0LmEHd3aMJfQrYCt",
    "Rachel Lopez": "5kMzVeC7TiFEK3aNCw1Z",
    "Lori - Happy and sweet": "TbMNBJ27fH2U0VgpSNko",
    "Michael C. Vincent": "uju3wxzG5OhpWcoi3SMy",
    "Nawlins Gentleman": "ERbFfgajma1nPOBNQw6U",
    "Mira - Meditation, Calming Down, Relaxing": "ZqvIIuD5aI9JFejebHiH",
    "Nigerian Voice Pro - NZ The African Man": "gsyHQ9kWCDIipR26RqQ1",
    "Flint - Commanding Presence": "qAZH0aMXY8tw1QufPN0D",
    "Prometheus": "7xztkfMJIOrrj9xwOK0T",
    "Matt - Real, Hyper-Conversational, Natural, Chatty, Friendly American Male": "pwMBn0SsmN1220Aorv15",
    "Olivia": "ChvixV5Kt063KajV05qE",
    "Reginald": "Hjzqw9NR0xFMYU9Us0DL",
    "Nick Insurance AI": "02N42Ac51lYGp3HHsqw2",
    "Robert - American standard broadcaster": "tNIuvXGG5RnGdTbvfnPR",
    "SARA IV VOICE": "d25lChSmx0iqNTDDiEob",
    "Layla": "atU6Ya4L94HvFNnxzdrl",
    "Robert - Business Book Narrator": "UQoLnPXvf18gaKpLzfb8",
    "Susan 4.7": "2PPBmSMbVEg53yAB8mge",
    "Saf - Your Soft-Spoken Dream Girl": "TB3vNRzK8VurMejP889qI",
    "Sam - Chill, Southern California Male": "ZRwrL4id6j1HPGFkeCzO",
    "Serafina - Flirty Sensual Temptress": "4tRn1lSkEn13EVTuqb0g",
    "Shanni - Sultry Adult Woman": "A6TsrDqI2qlO9AWAfZHY",
    "T $$$": "sBoUTk5i8hxxdbD6ZIyb",
    "Ron 2": "xkDz8dF9GIt1kG06c9Of",
    "Spence - Clear, Soft-Spoken American": "ZTho75k1M56OV0k9XtSC",
    "Stephen - Sales & Customer Service Voice AI Agent": "6YQMyaUWlj0VX652cY1C",
    "Robert Forrest": "mkZwO4JCm0yEo6WmjZjA",
    "Robert Stamp - Professional clear confident middle-aged American Male, delightful conversation": "s756tFIFJ9r8dOGB5rlK",
    "T $$$$ 2": "w5I2XphJYDdQx2g1mtfr",
    "Professor Bill": "lnieQLGTodpbhjpZtg1k",
    "Tommy VM": "372Lm1KOYTs21Azj4vLh",
    "rich example": "Ff0ah5pKb1Su9QdqKWaj",
    "barb 2.0": "fPACBvm6diGGJuOtybsH",
    "barb 3": "8EfaO9y3EVnC3qzvhp81",
    "new Clone with background": "kUjD3JQuhDqKYmDA57qC",
    "Timber – Southern US - Stories & Country Wisdom": "1gcivRWlUUhp7wLqy7GB",
    "Tony - Middle-aged with American accent ": "hP72SDESIJq2YuAblBqz",
    "W. Darth Oxley": "G3zrXA9moYrFCgwBAvxJ",
    "Tanya- Upbeat and Expressive": "Bwff1jnzl1s94AEcntUq",
    "W. Storytime Oxley": "iUqOXhMfiOIbBejNtfLR",
    "Waverly": "DveEBhc92f63T1jcpWTx",
    "🔥Havoc – Deep Southern Gothic Narrator, Gritty, Haunting, Legendary": "dtVZnErhiiosqofxDzSH",
    "Wyatt- Wise Rustic Cowboy": "YXpFCvM1S3JbWEJhoskW",
    "Zak - Narrator, Instructor and promoter": "tljqmZD3t7WiC49QlVHF"
};


export default voices